# Generated by Django 5.2.3 on 2025-06-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('subjects', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
    ]
