# Generated by Django 5.2.3 on 2025-06-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
